[[cascade]]
  [cascade.build]
    list             = 'always'
    publishResources = true
    render           = 'always'
  [cascade.target]
    path = '/content-formats/{asciidoc,pandoc,restructuredtext}'

[security]
  allowContent = ['.*']
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^node$', '^postcss$', '^tailwindcss$', '^babel$', '^asciidoctor$', '^pandoc$', '^rst2html$']
